### PR TITLE
43483-Rename library variable in pipeline YAML

### PR DESCRIPTION
**Pull request by tejasi15072**
Change terraform variable in azure-pipeline.yml and continuous-deployment-apim.yml file.

### CODE REVIEW

**Review by mattwin1 — COMMENTED** [review]
Need to fix small typo in 'SERIVCE' to 'SERVICE', otherwise fine

**Comment by barrie-cooper** [comment]
> Need to fix small typo in 'SERIVCE' to 'SERVICE', otherwise fine

Thanks for spotting that Matt.  They're also wrong in the ###### key vault! 😢 

I will correct thme there too before merging.

**Comment by tejasi15072** [comment]
Fixed the typo in yml files.

**Review by mattwin1 — APPROVED** [review]
👍

**Review by barrie-cooper — APPROVED** [review]
Thanks @tejasi15072

**Pull request merged**
